### ISSUE TITLE
Pokaż mapę z okolicznymi kampaniami

### ISSUE THREAD

**Issue by gogracek** [komitywa/wysadzulice.pl#109]
Na ekranie startowym widać mapę wg lokalizacji użytkownika. Jeśli użytkownik nie zgodzi się na autolokalizację - widok całej Polski.

Mapa pokazuje kampanie, które są aktywne (można do nich dołączyć).

**Comment by magul** [comment]
As says new version of #101:

```
AC4: W tle powinna być widoczna mapa Poznania (centrum) 
```

so it's not compatible with main story, so I'm removing epic.

**Comment by w1stler** [comment]
Closing this one because of #101
