### ISSUE TITLE
Pokaż miniatury innych kampanii

### ISSUE THREAD

**Issue by gogracek** [komitywa/wysadzulice.pl#110]
Pod mapą widać miniatury kampanii, odnoszące się do otwartego widoku mapy. Pojawiają się tam aktywne kampanie. Można je przewijać, jeśli jest ich więcej niż liczba mieszczących się miniatur w panelu.

**Comment by magul** [comment]
Because scope of #101 changed, I'm removing this issue from epic.

**Comment by w1stler** [comment]
Closing this one because of #136
