### ISSUE TITLE
Pokaż na mapie, gdzie jest kampania

### ISSUE THREAD

**Issue by gogracek** [komitywa/wysadzulice.pl#112]
Po najechaniu na miniaturę kampanii widać, gdzie się odbywa, jak np. tutaj:

![image](https://cloud.githubusercontent.com/assets/13927789/14685350/8f980924-0734-11e6-84e1-68739fa79e8f.png)

Możemy też użyć prostszego rozwiązania - np. na mapie widać od razu wszystkie kampanie (oznaczone guzikami). Po najechaniu na miniaturę guzik ją lokalizujący na mapie staje się bardziej widoczny - zmienia kolor na intensywny, zwiększa rozmiar.

**Comment by magul** [comment]
Scope of #101 changed and this story is out of it scope right now, so i'm removing it from epic.

**Comment by w1stler** [comment]
Closing this one because of #137
