### ISSUE TITLE
Fiksturki

### ISSUE THREAD

**Issue by d33tah** [komitywa/wysadzulice.pl#114]
Cześć,

Chciałbym pobawić się aplikacją, ale brakuje mi fiksturek a widok "nowej kampanii" nie działa (właściwie to go nie ma). Czy moglibyście dodać fiksturki, żebym mógł rozejrzeć się po aplikacji?

d33tah

**Comment by magul** [comment]
@d33tah Cześć! aplikacja jako taka nie wymaga żadnych fiksturek, żeby zacząć na niej działać poprawnie. Jedyne dane do bazy są zapisywane podczas migracji (https://github.com/komitywa/wysadzulice.pl/blob/master/wysadzulice/migrations/0005_auto_20160330_2106.py) - po wgraniu tej migracji baza jest w sumie gotowa.

Wnioskując jednocześnie po Twoim pull requeście to o czym zapomniałeś, to zbudowanie zależności nodejs'owych oraz dodanie pliku `wysadzulice_pl/secrets.py` zawierającego chociażby klucz Google Maps API.

Na chwilę obecną zamykam to isuse - jeżeli chodziło Tobie o coś innego, poproszę o reopen.

**Comment by magul** [comment]
A i jeszcze po zbudowaniu zależności nodejs-owych należy wykonać `gulp build`.
