### ISSUE TITLE
Wyróżnione kampanie - zarządzanie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#13]
JAKO administrator serwisu
CHCĘ wyróżnić kampanię
ABY była lepiej zauważalna na dla mieszkańców

**Comment by frublazej** [comment]
JAKO administrator serwisu wysadź
CHCĘ wyróżnić kampanię które mogą zostać zrealizowane w najbliższym czasie/są najlepsze
ABY była lepiej zauważalna dla mieszkańców/obserwatorów kampanii

**Comment by gogracek** [comment]
Nie robimy tego.
