### ISSUE TITLE
Plakat kampanii

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#14]
JAKO administrator kampanii
CHCĘ wydrukować plakat
ABY zaangażować mieszkańców offline
- nazwa
- zdjęcie
- adres
- call to action - "zaproponuj sówój pomysł na stronie", "wpadnij na spotkanie"
- link, np. wysadzulice.pl/plac_warynskiego

**Comment by gogracek** [comment]
W pierwszej wersji będzie sygnalizowanie potrzeb, nie projektowanie miejsca, dlatego zamykam wszystkie zadania związane z głosowaniem itp.
