### ISSUE TITLE
Głosowanie na wysadzenie - internauta

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#15]
JAKO internauta
CHCĘ zagłosować na wysadzenie
ABY pokazać poparcie dla danego wysadzenia
- 0 krok: podaj email (gdy użytkownik nie zarejestrowny)
- 1 krok: podoba się / nie podoba -> skala uczuć
- 2 krok: oceń użyteczność ze względu na różne grupy społeczne ()

**Comment by gogracek** [comment]
Zamykam, w pierwszej wersji WU będzie sygnalizowanie potrzeb, nie projektowanie miejsca i głosowanie na pomysły.
