### ISSUE TITLE
Chcę zorganizować głosowanie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#16]
JAKO organizator kampanii
CHCĘ zorganizować głosowanie
ABY wybrać najlepsze projekty
- określ termin głosowania
- opis (np. "wygrany projekt otrzyma pamiątkę - kostkę brukową")

**Comment by gogracek** [comment]
W pierwszej wersji będzie sygnalizowanie potrzeb, nie projektowanie miejsca, dlatego zamykam wszystkie zadania związane z głosowaniem itp.
