### ISSUE TITLE
Rejestrowanie użytkowników

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#17]
JAKO internauta
CHCĘ się zarejestrować 
ABY mieć dostęp do narzędzi aplikacji

Podaję mejla i wybieram hasło. Dostaję komunikat, że rejestracja się powiodła lub że istnieje już konto na tym mejlu.

**Comment by frublazej** [comment]
JAKO internauta
CHCĘ się zarejestrować
ABY móc tworzyć wysadzenia i zbierać je w kampanii(swojej)

mail / pass
opcjonalnie facebook / twitter
