### ISSUE TITLE
Tworzenie wysadzeń

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#18]
JAKO internauta
CHCĘ stworzyć wysadzenie w ramach kampanii
ABY podzielić się swoim pomysłem na zagospodarowanie przestrzeni

Lista kroków:
- wchodzę na listę kampanii
- wybieram kampanię
- klikam przycisk "Wysadź Ulicę"

**Comment by frublazej** [comment]
JAKO internauta
CHCĘ stworzyć wysadzenie w ramach kampanii która należy do niego
ABY aby dodać je do istniejących wysadzeń w tej kampanii
opcjonalnie ABY podać powód wysadzenia - opis wysadzenia
Lista kroków:

wchodzę na listę kampanii
wybieram kampanię - mogę ją edytować
klikam przycisk "Wysadź Ulicę" i rozpoczyna nowe wysadzenie
