### ISSUE TITLE
Logowanie użytkowników

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#19]
JAKO internauta
CHCĘ się zalogować
ABY mieć dostęp do narzędzi aplikacji

-logowanie poprzez pdoanie maila i hasła
-logowanie nie powiodło się -> 'ekran ponownego logowania'

**Comment by frublazej** [comment]
JAKO internauta
CHCĘ się zalogować
ABY mieć dostęp do galerii swoich wysadzeń i tworzenie kampanii oraz oceniania innych wysadzeń
