### ISSUE TITLE
Oglądanie listy kampanii

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#20]
JAKO internauta
CHCĘ zobaczyć listę kampanii
ABY zaangażować się, zaproponować wysadzenie w ramach kampanii

Galeria kampanii:
- fotka 
- nazwa

**Comment by frublazej** [comment]
JAKO internauta
CHCĘ zobaczyć listę kampanii
ABY zaangażować się, zaproponować wysadzenie w ramach kampanii

Galeria kampanii:

fotka
nazwa
przykładowa mapa wysadzeń - punkty wysadzeń

**Comment by magul** [comment]
O ile jest najprostsza lista kampanii, to nie spełnia kryteriów akceptacyjnych (fotka, nazwa).

Do refinementu i do new issues.

**Comment by gogracek** [comment]
Dublet.
