### ISSUE TITLE
Blog/newsletter kampanii

### ISSUE THREAD

**Issue by KrzysztofMadejski** [komitywa/wysadzulice.pl#25]
JAKO organizator kampanii
CHCĘ tworzyć aktualności
ABY informować wysadzaczy i innych interesariuszy o postępach kampanii
- dodanie aktualności (którą można wysłać mailem do wszystkich zainteresowanych (subskrybentów)
- subskrybenci:
  - wysadzacze, którzy wyrazili zgodę na informowanie
  - inne osoby zapisane na listę

**Comment by gogracek** [comment]
Na dalszym etapie może być potrzebne, teraz - nie jest.
