### ISSUE TITLE
Aplikacja na serwerze produkcyjnym podpięta pod mod_wsgi

### ISSUE THREAD

**Issue by magul** [komitywa/wysadzulice.pl#3]
Aplikacja na serwerze produkcyjnym powinna być podpięta pod serwer WWW (Apache) a nie serwowana za pomocą serwera wbudowanego w Django.

Więcej informacji można znaleźć na stronach:
- http://httpd.apache.org/
- https://code.google.com/p/modwsgi/
- https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/

**Comment by ron-welty** [comment]
Potrzebny bardziej szczegółowy opis dla pozostałych programistów.
