### ISSUE TITLE
Rozwijana aplikacja powinna działać pod adresem wysadzulice.pl

### ISSUE THREAD

**Issue by gogracek** [komitywa/wysadzulice.pl#31]
Rozwijana aplikacja powinna być dostępna światu pod adresem http://wysadzulice.pl

Aplikacja powinna być uruchamiana przez serwer www (Apache) w trybie mod_wsgi.

Więcej można znaleźć pod adresami:
- http://httpd.apache.org/
- https://code.google.com/p/modwsgi/
- https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/

**Comment by magul** [comment]
done in #33
