### ISSUE TITLE
Widok definiowania kampanii

### ISSUE THREAD

**Issue by magul** [komitywa/wysadzulice.pl#4]
Jako admin (ngo) chcę 
. wskazać miejsca do wysadzenia 
. opisać uczestnikom cel kampanii 
. pokazać uczestnikom miejsca na mapie i dać im call to action

**Comment by KrzysztofMadejski** [comment]
JAKO zarejestrowany uzytkownik
CHCĘ stworzyć kampanię 
ABY przedstawić jaki obszar chcemy zmienić

Kampania:
- czas trwania lub otwarta kampania
- lokalizacja (punkt = widok google street view)
- cel / oczekiwany efekt
- jak zostaną wykorzystane zgłoszone wysadzenia? (sugestie dla ekspertów, zbieram opinie, najlepszy projekt zostanie zrealizowany, ..)
- nazwa
- opis
- interesariusze (z kim współpracujesz nad projektem?)
- typy (konsultacje publiczne, budzet obywatelski, działania rady osiedla, partyzantka, ..)
- zdjęcia obecne
- budzet projektu (link do cennika miejskiego?)

**Comment by gogracek** [comment]
Epic. Rozbić na mniejsze historyjki.
