### ISSUE TITLE
Cel kampanii

### ISSUE THREAD

**Issue by magul** [komitywa/wysadzulice.pl#5]
Jako uczestnik (wysadzający) 
CHCĘ dowiedzieć się o celu kampanii
ŻEBY zdecydować, czy się w nią zaangażować

**Comment by magul** [comment]
@malepoludnie - tutaj mamy prostą tabelkę z linkiem "Create new planting" - da się wejść w wysadzenie, ale nie spełnia to Kryteriów Akceptacji.

Do ustalenia, czy/jak to robimy i do ewentualnego rozdzielenia na mniejsze taski.

**Comment by gogracek** [comment]
Będziemy to robić w ramach #4
