### ISSUE TITLE
Opis silnika na stronę dla programistów

### ISSUE THREAD

**Issue by pwl-walczak** [komitywa/wysadzulice.pl#66]
Magul, opisz silnik.

Pozostałe teksty będą wyglądać tak:
Hacknighty to cotygodniowe spotkania dedykowane rozwijaniu oddolnych projektów społeczno-technologicznych. Rozwijasz aplikację mobilną lub serwis internetowy? Wpadnij do nas, zaprezentuj się, poznaj ludzi, którzy kierują się podobnymi jak ty wartościami, znajdź osoby do współpracy i koduj.

Rytm cotygodniowych spotkań pozwoli ci stabilnie rozwijać projekt. W ramach Koduj dla Polski oferujemy także wsparcie w innych postaciach (zobacz http://www.slideshare.net/epforgpl/wsparcie-koduj-dla-polski-dla-projektw).

**Comment by magul** [comment]
@pwl-walczak, trzy sprawy:
- issue założyłeś nie w tym repozytorium - założę zaraz w poprawnym i jak chcesz być z nim na bieżąco to możesz się do niego zasuskrybować,
- strona, która docelowo ma trafić pod adres http://plantingjs.org będzie w języku angielskim
- strona będzie dotyczyć silnika (czyli tej części kodu, która znajduje się w repozytorium plantingjs) - nie widzę żadnej potrzeby, by pisać tam o hacknightach.

Zamykam.
