### ISSUE TITLE
URLs should be normallized

### ISSUE THREAD

**Issue by cmwd** [komitywa/wysadzulice.pl#92]
e.g:

http://wysadzulice.pl/campaigns/16/ is responding 404 code. 
But http://wysadzulice.pl/campaigns/16 works fine.

**Comment by magul** [comment]
We need add trailing slash in all pattersn set in https://github.com/komitywa/wysadzulice.pl/blob/master/wysadzulice/urls.py

And also we need to check if `APPEND_SLASH` is set to `True` https://docs.djangoproject.com/en/dev/ref/settings/#append-slash

**Comment by magul** [comment]
@rudymichal

**Comment by magul** [comment]
Done in #100
